### ISSUE TITLE
Reactmap can't get local.json

### ISSUE THREAD

**Issue by acocalypso** [acocalypso/ReactMapKubernetes#1]
yarn run v1.22.19
$ node .
/home/node/node_modules/config/lib/config.js:830
      throw new Error('Config file ' + fullFilename + ' cannot be read. Error code is: '+e2.code
      ^
Error: Config file /home/node/server/src/configs/local.json cannot be read. Error code is: EISDIR. Error message is: EISDIR: illegal operation on a directory, read
    at util.parseFile (/home/node/node_modules/config/lib/config.js:830:13)
    at /home/node/node_modules/config/lib/config.js:649:26
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (/home/node/node_modules/config/lib/config.js:648:16)
    at new Config (/home/node/node_modules/config/lib/config.js:113:27)
    at Object.<anonymous> (/home/node/node_modules/config/lib/config.js:1510:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Comment by acocalypso** [comment]
Fixes
